import test from 'node:test';import assert from 'node:assert/strict';import pg from 'pg';import {randomUUID} from 'node:crypto';
const url=process.env.LOCAL_DATABASE_URL;if(!/^postgresql:\/\/postgres@127\.0\.0\.1:\d+\/person_tenant_binding_test$/.test(url||''))throw Error('local fixture required');
const pool=new pg.Pool({connectionString:url,max:8});test.after(()=>pool.end());
const TT='801865a7-6533-41d2-9c45-e4a90e6ad51a',A=randomUUID(),B=randomUUID();
for(const org of [A,B])await pool.query('insert into organizations(id,slug) values($1,$2)',[org,`synthetic-tenant-${org}`]);
async function app(org=A,username=`synthetic-${randomUUID()}`,patch={},c=pool){const id=patch.id??randomUUID();await c.query("insert into website_applications(id,organization_id,name,email,linkedin_username,linkedin_url,status,source,created_at,person_processing_version) values($1,$2,'Synthetic','synthetic@example.test',$3,$4,'queued',$5,$6,1)",[id,org,username,username?`https://www.linkedin.com/in/${username}`:null,patch.source??'applied',patch.created_at??new Date().toISOString()]);return{id,org,username};}
async function claim(row,started=true){const token=randomUUID(),work=(await pool.query('select person_application_work_claim($1,$2,$3,900) result',[row.id,row.org,token])).rows[0].result;assert.equal(work.status,'admitted');if(started)await pool.query('select person_application_work_start($1,$2)',[work.work_id,token]);return{...row,token,work:work.work_id};}
async function bind(work,hook){const c=await pool.connect();try{await c.query('begin');await c.query("select set_config('request.headers',$1,true)",[JSON.stringify({'x-person-work-id':work.work,'x-person-work-token':work.token})]);if(hook)await hook(c);const result=(await c.query('select person_application_tenant_bind() result')).rows[0].result;await c.query('commit');return result;}finally{await c.query('rollback');c.release();}}
async function waiting(pid){for(let i=0;i<100;i++){if((await pool.query("select wait_event_type='Lock' waiting from pg_stat_activity where pid=$1",[pid])).rows[0]?.waiting)return;await new Promise(r=>setTimeout(r,5));}assert.fail('expected a real lock wait');}
test('TT hold does not prevent admitted tenant binding',async()=>{await pool.query("select person_private.transition_set('arm',1,1,'synthetic_test');select person_private.transition_set('drain',2,2,'synthetic_test');select person_private.transition_set('seal',3,2,'synthetic_test')");const w=await claim(await app());const r=await bind(w);assert.equal(r.person_key,w.id);assert.equal(r.organization_id,A);assert.equal(r.application_id,w.id);assert.equal(r.work_id,w.work);});
test('concurrent same-person work shares a frozen organization key',async()=>{const username=`same-${randomUUID()}`,a=await app(A,username,{created_at:'2001-01-01'}),b=await app(A,username,{created_at:'2001-01-02'}),works=await Promise.all([claim(a),claim(b)]);const results=await Promise.all(works.map(w=>bind(w)));assert.equal(results[0].person_key,a.id);assert.equal(results[1].person_key,a.id);assert.equal((await pool.query('select count(*)::int n from person_private.tenant_application_people where organization_id=$1 and linkedin_username=$2',[A,username])).rows[0].n,1);});
test('an earlier-dated later commit cannot retarget existing identity',async()=>{const username=`late-${randomUUID()}`,c=await pool.connect();try{await c.query('begin');const late=await app(A,username,{created_at:'2000-01-01'},c),first=await claim(await app(A,username));assert.equal((await bind(first)).person_key,first.id);await c.query('commit');assert.equal((await bind(await claim(late))).person_key,first.id);}finally{await c.query('rollback');c.release();}});
test('equal timestamps choose an application deterministically',async()=>{const username=`tie-${randomUUID()}`,ids=[randomUUID(),randomUUID()].sort();await app(A,username,{id:ids[1],created_at:'2001-01-01'});const row=await app(A,username,{id:ids[0],created_at:'2001-01-01'});assert.equal((await bind(await claim(row))).person_key,ids[0]);});
test('the same username never shares a key across organizations',async()=>{const username=`org-${randomUUID()}`,a=await claim(await app(A,username)),b=await claim(await app(B,username));assert.equal((await bind(a)).person_key,a.id);assert.equal((await bind(b)).person_key,b.id);});
test('missing username uses only its owned application and creates no shared mapping',async()=>{const w=await claim(await app(A,null)),before=(await pool.query('select count(*)::int n from person_private.tenant_application_people')).rows[0].n;assert.equal((await bind(w)).person_key,w.id);assert.equal((await pool.query('select count(*)::int n from person_private.tenant_application_people')).rows[0].n,before);await assert.rejects(pool.query('select person_application_tenant_bind()'),/transition_admission/);});
for(const state of ['unstarted','expired','uncertain','completed','wrong-token'])test(`${state} work cannot bind`,async()=>{const w=await claim(await app(),state!=='unstarted');if(state==='expired')await pool.query("update person_private.transition_work set lease_until=clock_timestamp()-interval '1 second' where id=$1",[w.work]);if(['uncertain','completed'].includes(state))await pool.query('update person_private.transition_work set status=$2 where id=$1',[w.work,state]);if(state==='wrong-token')w.token=randomUUID();await assert.rejects(bind(w),/transition_admission|transition_expired|transition_unresolved|application_effects_required/);});
for(const mutation of ['organization','username','source'])test(`a changed anchor ${mutation} fails without remapping`,async()=>{const username=`anchor-${randomUUID()}`,w=await claim(await app(A,username));await bind(w);const next=await claim(await app(A,username));if(mutation==='organization')await pool.query('update website_applications set organization_id=$2 where id=$1',[w.id,B]);if(mutation==='username')await pool.query("update website_applications set linkedin_username='synthetic-renamed' where id=$1",[w.id]);if(mutation==='source')await pool.query("update website_applications set source='transformer_talent' where id=$1",[w.id]);await assert.rejects(bind(next),/tenant_binding_anchor/);assert.equal((await pool.query('select application_id from person_private.tenant_application_people where organization_id=$1 and linkedin_username=$2',[A,username])).rows[0].application_id,w.id);});
test('TT-sent applications are excluded from selection and current admission',async()=>{const username=`sent-${randomUUID()}`;await app(A,username,{source:'transformer_talent',created_at:'2000-01-01'});const w=await claim(await app(A,username));assert.equal((await bind(w)).person_key,w.id);const sent=await claim(await app(A,`sent-current-${randomUUID()}`,{source:'transformer_talent'}));await assert.rejects(bind(sent),/application_scope|tenant_binding_scope/);});
test('an anchor cannot be deleted into an implicit remap',async()=>{const w=await claim(await app());await bind(w);await assert.rejects(pool.query('delete from website_applications where id=$1',[w.id]),/foreign key constraint/);assert.equal((await bind(w)).person_key,w.id);});
test('service may call the checked RPC but cannot edit its proof',async()=>{const w=await claim(await app());assert.equal((await bind(w,c=>c.query('set local role service_role'))).person_key,w.id);for(const table of ['tenant_application_people','tenant_application_bindings']){const c=await pool.connect();try{await c.query('begin');await c.query('set local role service_role');await assert.rejects(c.query(`delete from person_private.${table}`),/permission denied/);}finally{await c.query('rollback');c.release();}}});
test('tenant bindings never write TT pool or normalized storage',async()=>{for(const table of ['candidates','candidate_sources','candidate_profile_state','candidate_identities'])assert.equal((await pool.query(`select count(*)::int n from ${table}`)).rows[0].n,0);});
for(const lock of ['username','anchor'])test(`lease expiry during a real ${lock} wait rolls back binding`,async()=>{
 const username=`wait-${randomUUID()}`,owner=await claim(await app(A,username));if(lock==='anchor')await bind(owner);
 const w=lock==='anchor'?await claim(await app(A,username)):owner,locker=await pool.connect();let release;
 try{await locker.query('begin');if(lock==='username')await locker.query('select pg_advisory_xact_lock(72008,hashtext($1))',[A+':'+username]);else await locker.query('select id from website_applications where id=$1 for update',[owner.id]);
  await pool.query("update person_private.transition_work set lease_until=clock_timestamp()+interval '250 milliseconds' where id=$1",[w.work]);
  const operation=bind(w,async c=>{const pid=(await c.query('select pg_backend_pid() pid')).rows[0].pid;release=(async()=>{await waiting(pid);await new Promise(r=>setTimeout(r,280));await locker.query('rollback');})();});
  await assert.rejects(operation,/transition_expired|transition_admission/);await release;
  assert.equal((await pool.query('select count(*)::int n from person_private.tenant_application_bindings where work_id=$1',[w.work])).rows[0].n,0);
  assert.equal((await pool.query('select count(*)::int n from person_private.tenant_application_people where organization_id=$1 and linkedin_username=$2',[A,username])).rows[0].n,lock==='username'?0:1);
 }finally{await locker.query('rollback');if(release)await release;locker.release();}
});
test('changed current ownership cannot borrow its earlier reservation',async()=>{const w=await claim(await app());await pool.query('update website_applications set organization_id=$2 where id=$1',[w.id,B]);await assert.rejects(bind(w),/tenant_binding_scope/);});
test('TT work cannot enter the tenant bridge',async()=>{await pool.query("select person_private.transition_set('disarm',4,3,'synthetic_test')");const w=await claim(await app(TT));await assert.rejects(bind(w),/application_scope/);});
