import test from 'node:test';import assert from 'node:assert/strict';import pg from 'pg';import {randomUUID} from 'node:crypto';
const url=process.env.LOCAL_DATABASE_URL;if(!/^postgresql:\/\/postgres@127\.0\.0\.1:\d+\/person_legacy_sources_test$/.test(url||''))throw Error('local fixture required');const pool=new pg.Pool({connectionString:url,max:8});test.after(()=>pool.end());const TT='801865a7-6533-41d2-9c45-e4a90e6ad51a';
const ALT=randomUUID();await pool.query('insert into organizations(id,slug) values($1,$2)',[ALT,'synthetic-legacy-'+ALT]);
const phase=enabled=>pool.query("update person_private.transition_control set enabled=$1,phase='open' where singleton",[enabled]);test.beforeEach(()=>phase(true));
async function tx(fn,role=false){const c=await pool.connect();try{await c.query('begin');if(role)await c.query('set local role service_role');const r=await fn(c);await c.query('commit');return r;}finally{await c.query('rollback');c.release();}}
async function seed(table,source='harvest'){await phase(false);try{const id=randomUUID(),cid=randomUUID();if(table==='candidate_experiences')await pool.query("insert into candidate_experiences(id,candidate_id,organization_id,source,title) values($1,$2,$3,$4,'Synthetic')",[id,cid,TT,source]);else await pool.query("insert into candidate_communications(id,recruiter_id,candidate_id,communication_type,status) values($1,1,$2,'email','replied')",[id,cid]);return{id,cid};}finally{await phase(true);}}
const fingerprints=async cid=>(await pool.query("select (select md5(coalesce(string_agg(to_jsonb(e)::text,',' order by id),'')) from person_change_events e where candidate_id=$1) events,(select md5(coalesce(string_agg(to_jsonb(q)::text,',' order by candidate_id),'')) from person_change_queue q where candidate_id=$1) queue",[cid])).rows[0];
for(const table of ['candidate_communications','candidate_experiences'])for(const role of [false,true])for(const op of ['insert','update','delete'])test(`${role?'service':'owner'} raw ${table} ${op} leaves sources and capture unchanged`,async()=>{const {id,cid}=await seed(table),before=await fingerprints(cid);let sql,args=[id];if(op==='delete')sql=`delete from ${table} where id=$1`;else if(op==='update')sql=`update ${table} set ${table==='candidate_experiences'?"title='Changed'":"status='bounced'"} where id=$1`;else{args=[randomUUID(),cid,TT];sql=table==='candidate_experiences'?"insert into candidate_experiences(id,candidate_id,organization_id,source) values($1,$2,$3,'harvest')":"insert into candidate_communications(id,recruiter_id,candidate_id,communication_type) values($1,1,$2,'email')";if(table==='candidate_communications')args.pop();}await assert.rejects(tx(c=>c.query(sql,args),role),/legacy_(communication|experience)_fence/);assert.deepEqual(await fingerprints(cid),before);});
for(const kind of ['source','candidate','organization'])test(`legacy experience ${kind} change cannot escape ownership`,async()=>{const {id}=await seed('candidate_experiences');await assert.rejects(pool.query(kind==='source'?"update candidate_experiences set source='person' where id=$1":`update candidate_experiences set ${kind==='candidate'?'candidate_id':'organization_id'}=$2 where id=$1`,kind==='source'?[id]:[id,kind==='organization'?ALT:randomUUID()]),/legacy_experience_fence|normalization_frame/);});
test('person rows cannot become raw source rows',async()=>{const {id}=await seed('candidate_experiences','person');await assert.rejects(pool.query("update candidate_experiences set source='harvest' where id=$1",[id]),/legacy_experience_fence|normalization_frame/);});
test('legacy source context cannot be selected by partial credentials while disabled',async()=>{await phase(false);await assert.rejects(tx(async c=>{await c.query("set local person.work_token='00000000-0000-4000-8000-000000000001'");await c.query("insert into candidate_communications(recruiter_id,candidate_id,communication_type) values(1,$1,'email')",[randomUUID()]);}),/legacy_communication_fence/);});
test('owner TRUNCATE cannot remove source evidence',async()=>{for(const table of ['candidate_communications','candidate_experiences'])await assert.rejects(pool.query(`truncate ${table} cascade`),/audit_proof_truncate|legacy_source_truncate/);});
test('disabled legacy writes remain available',async()=>{const a=await seed('candidate_communications'),b=await seed('candidate_experiences');await phase(false);await pool.query("update candidate_communications set status='bounced' where id=$1",[a.id]);await pool.query("update candidate_experiences set title='Legacy' where id=$1",[b.id]);await pool.query('delete from candidate_communications where id=$1',[a.id]);await pool.query('delete from candidate_experiences where id=$1',[b.id]);});
async function waitBlocked(name){for(let i=0;i<100;i++){if((await pool.query('select exists(select 1 from pg_stat_activity where application_name=$1 and wait_event_type=$2) b',[name,'Lock'])).rows[0].b)return;await new Promise(r=>setTimeout(r,10));}assert.fail('actual lock wait not observed');}
for(const table of ['candidate_communications','candidate_experiences'])test(`controller arm waits behind an already-started ${table} statement`,async()=>{await phase(false);const writer=await pool.connect(),control=await pool.connect();let pending;try{await writer.query('begin');await writer.query(`update ${table} set candidate_id=candidate_id where false`);const c=(await pool.query('select revision,generation from person_private.transition_control where singleton')).rows[0];await control.query("set application_name='synthetic-legacy-arm'");pending=control.query("select person_private.transition_set('arm',$1,$2,'synthetic_test')",[c.revision,c.generation]).then(r=>r,e=>e);await waitBlocked('synthetic-legacy-arm');await writer.query('commit');const result=await pending;assert.ok(result.rows,result.message);}finally{await writer.query('rollback');if(pending)await pending;writer.release();control.release();}});
test('a writer waiting behind controller arm sees the new refusal',async()=>{const {id}=await seed('candidate_communications');await phase(false);const c=await pool.connect(),writer=await pool.connect();let pending;try{await c.query('begin');const v=(await c.query('select revision,generation from person_private.transition_control where singleton')).rows[0];await c.query("select person_private.transition_set('arm',$1,$2,'synthetic_test')",[v.revision,v.generation]);await writer.query("set application_name='synthetic-legacy-writer'");pending=writer.query('update candidate_communications set status=status where id=$1',[id]).then(()=>null,e=>e);await waitBlocked('synthetic-legacy-writer');await c.query('commit');assert.match((await pending)?.message||'',/legacy_communication_fence/);}finally{await c.query('rollback');if(pending)await pending;c.release();writer.release();}});
test('stale repeatable-read snapshots cannot use the disabled state after arm',async()=>{const {id}=await seed('candidate_communications');await phase(false);const reader=await pool.connect();try{await reader.query('begin isolation level repeatable read');const c=(await reader.query('select revision,generation from person_private.transition_control where singleton')).rows[0];await pool.query("select person_private.transition_set('arm',$1,$2,'synthetic_test')",[c.revision,c.generation]);await assert.rejects(reader.query('update candidate_communications set status=status where id=$1',[id]),/could not serialize|legacy_communication_fence/);}finally{await reader.query('rollback');reader.release();}});
test('tenant binding and completion remain available while TT is held',async()=>{await pool.query("update person_private.transition_control set phase='held' where singleton");const username='synthetic-tenant-'+randomUUID(),a=(await pool.query("select person_application_accept('apply',$1) r",[{organization_id:ALT,name:'Synthetic',email:'synthetic@example.test',linkedin_username:username,linkedin_url:'https://www.linkedin.com/in/'+username,preferred_locations:[],role_ids:[],role_titles:[]}])).rows[0].r,token=randomUUID(),w=(await pool.query('select person_application_work_claim($1,$2,$3,900) r',[a.id,ALT,token])).rows[0].r;assert.equal(w.status,'admitted');await pool.query('select person_application_work_start($1,$2)',[w.work_id,token]);await tx(async c=>{await c.query("select set_config('request.headers',$1,true)",[JSON.stringify({'x-person-work-id':w.work_id,'x-person-work-token':token})]);await c.query('select person_application_tenant_bind()');assert.equal((await c.query('select person_application_work_complete($1) r',[{version:1,matched_role_ids:[],screening:null,name:'Synthetic',harvest_profile:null,parsed_profile:null,resume_text:null,resume_contacts:{phone:null,emails:[]}}])).rows[0].r.status,'completed');});assert.equal((await pool.query('select count(*)::int n from candidates')).rows[0].n,0);});
test('role and shared lookup reads plus anonymous JD telemetry remain available',async()=>{for(const table of ['org_roles','companies','schools','skills'])await tx(c=>c.query(`select count(*) from ${table}`),true);await pool.query("insert into candidate_enrichments(organization_id,provider,operation) values($1,'llamaparse','jd_parse')",[TT]);});
