import test from 'node:test';import assert from 'node:assert/strict';import pg from 'pg';import {randomUUID} from 'node:crypto';
const url=process.env.LOCAL_DATABASE_URL;if(!/^postgresql:\/\/postgres@127\.0\.0\.1:\d+\/person_(?:conflict_evidence|lookup_mutations|directory_input|directory_execution|directory_publication)_test$/.test(url||''))throw Error('local fixture required');const pool=new pg.Pool({connectionString:url,max:8});test.after(()=>pool.end());
const phase=enabled=>pool.query("update person_private.transition_control set enabled=$1,phase='open' where singleton",[enabled]);test.beforeEach(()=>phase(true));
async function tx(fn,role=false){const c=await pool.connect();try{await c.query('begin');if(role)await c.query('set local role service_role');const r=await fn(c);await c.query('commit');return r;}finally{await c.query('rollback');c.release();}}
async function seed(){await phase(false);try{return(await pool.query("insert into identity_conflicts(kind,candidate_ids,incoming,evidence_hash) values('identity_taken',array[$1::uuid],'{}',$2) returning *",[randomUUID(),randomUUID().replaceAll('-','')])).rows[0];}finally{await phase(true);}}
for(const role of [false,true])for(const op of ['insert','resolve','delete'])test(`${role?'service':'owner'} cannot ${op} raw conflict evidence while required`,async()=>{const row=await seed();await assert.rejects(tx(c=>op==='insert'?c.query("insert into identity_conflicts(kind,candidate_ids,incoming,evidence_hash) values('identity_taken',array[$1::uuid],'{}',$2)",[randomUUID(),randomUUID().replaceAll('-','')]):c.query(op==='delete'?'delete from identity_conflicts where id=$1':"update identity_conflicts set status='resolved' where id=$1",[row.id]),role),/conflict_evidence_/);assert.deepEqual((await pool.query('select * from identity_conflicts where id=$1',[row.id])).rows[0],row);});
test('owner cannot truncate conflict evidence',async()=>{await assert.rejects(pool.query('truncate identity_conflicts'),/audit_proof_truncate|conflict_evidence_/);});
test('partial work credentials do not select the disabled legacy path',async()=>{await phase(false);await assert.rejects(tx(async c=>{await c.query("set local person.work_token='00000000-0000-4000-8000-000000000001'");await c.query("insert into identity_conflicts(kind) values('identity_taken')");}),/conflict_evidence_/);});
test('disabled raw conflict handling and historical helper remain compatible',async()=>{const row=await seed();await phase(false);await tx(async c=>{await c.query("update identity_conflicts set status='resolved' where id=$1",[row.id]);await c.query('delete from identity_conflicts where id=$1',[row.id]);assert.equal((await c.query('select person_backfill_flag_missing_employers($1) n',[randomUUID()])).rows[0].n,0);},true);});
test('service cannot call the insertion helper or fabricate a private frame',async()=>{
 assert.equal((await pool.query("select has_function_privilege('service_role','person_private.conflict_insert(text,uuid[],jsonb,text,uuid)','EXECUTE') allowed")).rows[0].allowed,false);
 await assert.rejects(tx(c=>c.query('insert into person_private.conflict_frames select * from person_private.conflict_frames where false'),true),/permission denied/);
});
async function waitLock(pid){for(let i=0;i<100;i++){const r=(await pool.query("select wait_event_type='Lock' waiting from pg_stat_activity where pid=$1",[pid])).rows[0];if(r?.waiting)return;await new Promise(r=>setTimeout(r,5));}assert.fail('expected real lock wait');}
test('legacy conflict statement holds controller lock until commit',async()=>{
 await phase(false);const legacy=await pool.connect(),control=await pool.connect();let pending;
 try{await legacy.query('begin');await legacy.query("insert into identity_conflicts(kind,evidence_hash) values('identity_taken',$1)",[randomUUID()]);const pid=(await control.query('select pg_backend_pid() pid')).rows[0].pid;pending=control.query('update person_private.transition_control set enabled=true where singleton');await waitLock(pid);await legacy.query('commit');await pending;}finally{await legacy.query('rollback');if(pending)await pending;legacy.release();control.release();}
});
test('waiting legacy statement rechecks armed state before evidence mutation',async()=>{
 await phase(false);const control=await pool.connect(),legacy=await pool.connect();let pending;
 try{await control.query('begin');await control.query('update person_private.transition_control set enabled=true where singleton');const pid=(await legacy.query('select pg_backend_pid() pid')).rows[0].pid;pending=legacy.query("insert into identity_conflicts(kind,evidence_hash) values('identity_taken',$1)",[randomUUID()]).then(()=>null,e=>e);await waitLock(pid);await control.query('commit');assert.match((await pending)?.message||'',/conflict_evidence_/);}finally{await control.query('rollback');if(pending)await pending;control.release();legacy.release();}
});
