// Produces the immutable SQL validator's literal from the same JS Unicode
// categories used by applicants.ts. Regenerate deliberately on parser upgrades.
const ranges=[];let start=null;
for(let cp=0;cp<=0x110000;cp++){
 const ok=cp<0x110000&&(/[\p{L}\p{N}\p{M}]/u.test(String.fromCodePoint(cp))||[45,46,95].includes(cp));
 if(ok&&start===null)start=cp;
 if(!ok&&start!==null){ranges.push(`[${start},${cp})`);start=null;}
}
console.log(`-- Generated by scripts/person-application-acceptance/unicode-ranges.mjs; Unicode ${process.versions.unicode}.`);
console.log(`create function person_private.application_accept_username(p text) returns boolean language sql immutable set search_path='' as $$\n select coalesce(length(p) between 1 and 200 and not exists(select 1 from regexp_split_to_table(p,'') ch where not ('{${ranges.join(',')}}'::int4multirange @> ascii(ch))),false)\n$$;`);
